# Generated by Django 6.0.5 on 2026-05-15 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(unique=True)),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('genres', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('crew', models.JSONField(blank=True, default=list)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='data.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='data.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('adult', models.BooleanField(default=False)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, max_length=500)),
                ('original_language', models.CharField(blank=True, max_length=20)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('tagline', models.TextField(blank=True)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('belongs_to_collection', models.JSONField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('production_companies', models.JSONField(blank=True, default=list)),
                ('production_countries', models.JSONField(blank=True, default=list)),
                ('spoken_languages', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='data.movie')),
            ],
        ),
        migrations.CreateModel(
            name='GenomeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField()),
                ('genome_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_scores', to='data.genometag')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_scores', to='data.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['movie'], name='data_genome_movie_i_2954b9_idx'), models.Index(fields=['genome_tag'], name='data_genome_genome__5440dd_idx')],
                'unique_together': {('movie', 'genome_tag')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='data.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='data_rating_user_id_a82a2e_idx'), models.Index(fields=['movie'], name='data_rating_movie_i_cf7f38_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'movie', 'timestamp'), name='unique_user_movie_rating_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('timestamp', models.BigIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='data.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='data_tag_user_id_1b3598_idx'), models.Index(fields=['movie'], name='data_tag_movie_i_99ecb7_idx'), models.Index(fields=['tag'], name='data_tag_tag_a5d4e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'movie', 'tag', 'timestamp'), name='unique_user_movie_tag_timestamp')],
            },
        ),
    ]
