# Generated by Django 6.0.5 on 2026-05-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielink',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
