# Generated by Django 6.0.5 on 2026-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_moviemetadata_homepage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecredits',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='moviecredits',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
