# Generated by Django 6.0.5 on 2026-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_moviecredits_tmdb_id_moviecredits_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemetadata',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
