# Generated by Django 6.0.5 on 2026-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_moviemetadata_backdrop_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemetadata',
            name='backdrop_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
