# Generated by Django 6.0.5 on 2026-06-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_moviemetadata_backdrop_path_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_genome_tags', models.JSONField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genome_profile', to='data.movie')),
            ],
        ),
    ]
