# Generated by Django 6.0.5 on 2026-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_genomerecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomerecommendation',
            name='recommended_movies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
