# Generated by Django 6.0.5 on 2026-06-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_genomerecommendation_recommended_movies'),
    ]

    operations = [
    ]
