# Generated by Django 6.0.5 on 2026-06-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20260604_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenomeRecommendation',
        ),
    ]
