# Generated by Django 6.0.5 on 2026-06-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_delete_genomerecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_movies', models.JSONField(blank=True, default=list)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genome_recommendation', to='data.movie')),
            ],
        ),
    ]
